name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        
      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Initialize SonarCloud Scanner
        run: dotnet sonarscanner begin /k:"amoroziuk_usecase1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /o:"amoroziuk"

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Run Tests (Optional)
        run: dotnet test --no-build --verbosity normal

      - name: Run SonarCloud Scanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
